import { promises as fs } from "node:fs";
import path from "node:path";
import type { Project, ProjectTask, RunRecord, RunWorkspace } from "@maestro/core";
import { readRunMetadata } from "./run-prepare";

export interface HandoffPackageResult {
  handoffDir: string;
  files: string[];
}

const HANDOFF_FILES = [
  "00-read-this-first.md",
  "01-executor-rules.md",
  "02-approved-codex-plan.md",
  "03-project-context.md",
  "04-task-contract.md",
  "05-expected-report-format.md",
  "06-do-not-touch.md",
  "07-kiro-prompt.md"
];

export async function createHandoffPackage(
  run: RunRecord,
  project: Project,
  task?: ProjectTask,
  workspace?: RunWorkspace
): Promise<HandoffPackageResult> {
  const handoffDir = path.join(run.path, "handoff");
  await fs.mkdir(handoffDir, { recursive: true });

  const supervisorOutput = await readRunFile(run, "07-supervisor-output.md");
  if (!supervisorOutput) {
    throw new Error("Cannot create handoff package: supervisor output is missing. Run 'maestro run attach --stage supervisor' first.");
  }

  const contextPack = await readRunFile(run, "02-context-pack.md");
  const metadata = await readRunMetadata(run.path);

  await fs.writeFile(path.join(handoffDir, "00-read-this-first.md"), renderReadThisFirst(workspace), "utf8");
  await fs.writeFile(path.join(handoffDir, "01-executor-rules.md"), renderExecutorRules(workspace), "utf8");
  await fs.writeFile(path.join(handoffDir, "02-approved-codex-plan.md"), supervisorOutput, "utf8");
  await fs.writeFile(path.join(handoffDir, "03-project-context.md"), renderProjectContext(contextPack), "utf8");
  await fs.writeFile(path.join(handoffDir, "04-task-contract.md"), renderTaskContract(run, project, task, supervisorOutput, workspace), "utf8");
  await fs.writeFile(path.join(handoffDir, "05-expected-report-format.md"), renderExpectedReportFormat(), "utf8");
  await fs.writeFile(path.join(handoffDir, "06-do-not-touch.md"), renderDoNotTouch(project, metadata, workspace), "utf8");
  await fs.writeFile(path.join(handoffDir, "07-kiro-prompt.md"), renderKiroPrompt(run, project, task, workspace), "utf8");

  return {
    handoffDir,
    files: HANDOFF_FILES
  };
}

function renderReadThisFirst(workspace: RunWorkspace | undefined): string {
  return `# Read This First

## What is this package?

This handoff package was generated by Maestro to provide you (Kiro Executor) with everything you need to execute a task safely and professionally.

## Key Points

- **The Codex Supervisor has already planned this task.** You are the executor, not the architect.
- **Your role is to implement the approved plan**, not to redesign the system.
- **If you encounter conflicts or ambiguities**, stop and report them. Do not make large architectural decisions on your own.
- **Follow the execution rules** in \`01-executor-rules.md\`.
- **Use the approved plan** in \`02-approved-codex-plan.md\` as your primary guide.
- **When finished**, generate your report using the exact format in \`05-expected-report-format.md\`.
${renderWorkspaceNotice(workspace)}

## Workflow

1. Read this file.
2. Read \`01-executor-rules.md\` to understand your constraints.
3. Read \`02-approved-codex-plan.md\` to understand what to implement.
4. Read \`03-project-context.md\` to understand the project.
5. Read \`04-task-contract.md\` to understand the task details.
6. Read \`05-expected-report-format.md\` to understand the required report format.
7. Read \`06-do-not-touch.md\` to understand what files/folders to avoid.
8. Use \`07-kiro-prompt.md\` as your execution prompt (copy and paste it).

## After Execution

After you finish implementing:

1. Generate your report following \`05-expected-report-format.md\`.
2. The human operator will run \`maestro run capture-diff --run <run-id>\` to capture the real Git diff.
3. The human operator will attach your report: \`maestro run attach --run <run-id> --stage executor --file <your-report.md>\`.
4. The Codex Reviewer will review your work against the approved plan and the real diff.

## Important

- **Do not expand scope.** Implement only what the Codex Supervisor approved.
- **Do not refactor unrelated code.** Stay focused on the task.
- **Do not change dependencies** unless explicitly instructed.
- **Do not modify folder structure** without approval.
- **Do not remove existing functionality** unless explicitly instructed.
- **Preserve the project's existing style and conventions.**

If something is unclear or requires a decision outside the approved plan, **stop and ask for clarification** rather than proceeding on your own.
`;
}

function renderExecutorRules(workspace: RunWorkspace | undefined): string {
  return `# Executor Rules

These rules are **mandatory**. Violating them will result in rejection during review.

${renderWorkspaceNotice(workspace)}

## Core Rules

1. **Follow the Codex Supervisor plan strictly.** Do not deviate from the approved plan.
2. **Do not implement extra scope.** Only implement what was approved.
3. **Do not refactor files outside the necessary scope.** Stay focused on the task.
4. **Do not alter dependencies without explicit instruction.** No surprise package additions or removals.
5. **Do not change folder structure without approval.** Keep the project organization intact.
6. **Do not remove existing functionality.** Only add or modify as instructed.
7. **Preserve the project's existing style and conventions.** Match the codebase style.
8. **Before making large changes, explain your plan.** Give the human operator a chance to review.
9. **At the end, report all changed files, tests, and risks.** Use the required report format.
10. **If something is ambiguous, stop and ask for review.** Do not guess or assume.

## What to Avoid

- **Do not automate account creation, provider rotation, or provider limit bypassing.**
- **Do not add features that were not requested.**
- **Do not change APIs or data contracts without explicit approval.**
- **Do not introduce new architectural patterns without approval.**
- **Do not change build tools, test frameworks, or CI/CD without approval.**

## What to Do

- **Read the approved plan carefully.**
- **Understand the project context before coding.**
- **Implement the plan as specified.**
- **Write tests if the plan requires them.**
- **Run existing tests to ensure no regressions.**
- **Document your changes clearly in the report.**
- **List all files you modified.**
- **Report any risks, questions, or pending work.**

## If You Encounter Problems

- **If the plan is unclear**, stop and report the ambiguity.
- **If the plan conflicts with the codebase**, stop and report the conflict.
- **If you need to make a decision outside the plan**, stop and ask for approval.
- **If you discover a bug or issue**, report it in your final report.

## Success Criteria

Your work will be approved if:

- You followed the approved plan.
- You did not expand scope.
- You did not introduce unnecessary changes.
- You preserved the project's style and conventions.
- You reported all changes, tests, and risks clearly.
- The real Git diff matches the approved plan.
`;
}

function renderProjectContext(contextPack: string | undefined): string {
  if (!contextPack) {
    return `# Project Context

**Warning:** Context pack is missing. This should not happen. Contact the operator.
`;
  }

  return `# Project Context

${contextPack}
`;
}

function renderTaskContract(
  run: RunRecord,
  project: Project,
  task: ProjectTask | undefined,
  supervisorPlan: string,
  workspace: RunWorkspace | undefined
): string {
  const acceptanceCriteria = extractAcceptanceCriteria(supervisorPlan);

  return `# Task Contract

## Run Information

${renderWorkspaceNotice(workspace)}

- **Run ID:** ${run.id}
- **Project ID:** ${project.id}
- **Project Name:** ${project.name}
- **Task ID:** ${task?.id || "none"}
- **Created At:** ${run.createdAt}
- **Workspace Sandbox:** ${workspace?.workspacePath || "not created"}
- **Original Repository:** ${project.repoPath}

## Objective

${run.goal}

${task ? `## Task Details

- **Title:** ${task.title}
- **Description:** ${task.description || "Not set"}
- **Status:** ${task.status}
- **Priority:** ${task.priority}
- **Tags:** ${task.tags.length > 0 ? task.tags.join(", ") : "none"}
` : ""}

## Acceptance Criteria

${acceptanceCriteria}

## Contract

By executing this task, you agree to:

- Follow the approved Codex Supervisor plan.
- Implement only the approved scope.
- Report all changes, tests, and risks.
- Use the required report format.
- Stop and ask if anything is unclear.
`;
}

function extractAcceptanceCriteria(supervisorPlan: string): string {
  const lines = supervisorPlan.split(/\r?\n/);
  const criteriaKeywords = [
    "acceptance criteria",
    "critérios de aceite",
    "criterios de aceite",
    "validation",
    "validação",
    "validacion",
    "checklist",
    "tests",
    "testes"
  ];

  let startIndex = -1;
  let endIndex = -1;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].toLowerCase().trim();
    if (criteriaKeywords.some(keyword => line.includes(keyword))) {
      startIndex = i;
      break;
    }
  }

  if (startIndex === -1) {
    return "_Acceptance criteria not automatically extracted. Review the approved Codex plan in 02-approved-codex-plan.md._";
  }

  for (let i = startIndex + 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line.startsWith("##") || line.startsWith("# ")) {
      endIndex = i;
      break;
    }
  }

  if (endIndex === -1) {
    endIndex = lines.length;
  }

  const extracted = lines.slice(startIndex, endIndex).join("\n").trim();
  return extracted || "_Acceptance criteria not automatically extracted. Review the approved Codex plan in 02-approved-codex-plan.md._";
}

function renderExpectedReportFormat(): string {
  return `# Expected Report Format

When you finish executing the task, generate your report using **exactly this format**:

\`\`\`markdown
# Relatório do Executor Kiro

## Resumo

[Provide a brief summary of what you implemented]

## Arquivos alterados

[List all files you created, modified, or deleted]

- path/to/file1.ts
- path/to/file2.ts
- path/to/file3.ts

## O que foi implementado

[Describe what you implemented, referencing the approved plan]

## O que não foi implementado

[List anything from the approved plan that you did NOT implement, and explain why]

## Testes/validações executadas

[List all tests you ran, checks you performed, or validations you completed]

## Riscos ou dúvidas

[Report any risks, concerns, or questions you have about the implementation]

## Pontos que precisam de revisão do Codex

[Highlight specific areas where you want the Codex Reviewer to pay extra attention]

## Confirmação

- [ ] Segui o plano do Codex Supervisor
- [ ] Não alterei escopo extra
- [ ] Não alterei dependências sem necessidade
- [ ] Não modifiquei arquivos fora do necessário
- [ ] Listei todos os arquivos alterados
\`\`\`

## Important Notes

- **Use this exact format.** The Codex Reviewer expects this structure.
- **Be thorough.** List all files, tests, and risks.
- **Be honest.** If you deviated from the plan, explain why.
- **Be clear.** The Codex Reviewer will compare your report with the real Git diff.
- **Check all boxes** in the Confirmação section if they are true.
`;
}

function renderDoNotTouch(project: Project, metadata: any, workspace: RunWorkspace | undefined): string {
  const ignoredPatterns = [
    ".git/",
    "node_modules/",
    "dist/",
    "build/",
    "out/",
    ".next/",
    ".nuxt/",
    "target/",
    "bin/",
    "obj/",
    "*.lock (unless explicitly instructed)",
    "package-lock.json (unless explicitly instructed)",
    "yarn.lock (unless explicitly instructed)",
    "pnpm-lock.yaml (unless explicitly instructed)",
    ".env",
    ".env.local",
    ".env.production",
    "Files outside the task scope"
  ];

  return `# Do Not Touch

These files and folders should **not be modified** unless explicitly instructed in the approved plan.

## Standard Exclusions

${ignoredPatterns.map(pattern => `- ${pattern}`).join("\n")}

## Project-Specific Exclusions

${metadata.snapshotIgnorePatterns && metadata.snapshotIgnorePatterns.length > 0
    ? metadata.snapshotIgnorePatterns.map((pattern: string) => `- ${pattern}`).join("\n")
    : "- None configured"}

## Repository Path

- **Repository:** ${project.repoPath}
- **Workspace sandbox:** ${workspace?.workspacePath || "not created"}

## Important

- **Work only in the workspace sandbox when it exists.**
- **Do not modify the original repository path.**
- **Do not modify files outside the task scope.**
- **Do not touch configuration files** unless the approved plan explicitly requires it.
- **Do not modify lock files** unless the approved plan explicitly requires adding or updating dependencies.
- **Do not touch .env files** or other secret/credential files.
- **Do not modify .git/** or version control metadata.

If the approved plan requires modifying any of these files, proceed carefully and document the change clearly in your report.
`;
}

function renderKiroPrompt(run: RunRecord, project: Project, task: ProjectTask | undefined, workspace: RunWorkspace | undefined): string {
  return `# Kiro Executor Prompt

**Copy and paste this prompt into Kiro to execute the task.**

---

Você é o Kiro Executor dentro do fluxo Maestro.

O Codex Supervisor já analisou o projeto e aprovou o plano abaixo. Sua função é executar esse plano com precisão, sem expandir escopo e sem tomar decisões arquiteturais grandes sozinho.

## Informações da Run

${renderWorkspaceNotice(workspace)}

- **Run ID:** ${run.id}
- **Project:** ${project.name} (${project.id})
- **Task ID:** ${task?.id || "none"}
${task ? `- **Task Title:** ${task.title}` : ""}

## Objetivo

${run.goal}

## Regras Obrigatórias

Leia e siga as regras em \`handoff/01-executor-rules.md\`.

Resumo das regras principais:

1. Siga o plano do Codex Supervisor estritamente.
2. Não implemente escopo extra.
3. Não refatore arquivos fora do necessário.
4. Não altere dependências sem instrução explícita.
5. Não mude estrutura de pastas sem aprovação.
6. Não remova funcionalidades existentes.
7. Preserve o estilo do projeto.
8. Antes de mudanças grandes, explique o plano.
9. Ao final, reporte arquivos alterados, testes e riscos.
10. Se algo estiver ambíguo, pare e peça revisão.

## Plano Aprovado do Codex Supervisor

Leia o plano completo em \`handoff/02-approved-codex-plan.md\`.

## Contexto do Projeto

Leia o contexto completo em \`handoff/03-project-context.md\`.

## Contrato da Task

Leia o contrato completo em \`handoff/04-task-contract.md\`.

## Arquivos e Pastas Proibidos

Leia a lista completa em \`handoff/06-do-not-touch.md\`.

Não toque em:

- .git/
- node_modules/
- dist/, build/, out/
- Arquivos de lock (exceto se o plano pedir explicitamente)
- .env
- Arquivos fora do escopo da task

## Formato de Relatório Obrigatório

Ao terminar, gere o relatório **exatamente** no formato especificado em \`handoff/05-expected-report-format.md\`.

O relatório deve incluir:

- Resumo
- Arquivos alterados
- O que foi implementado
- O que não foi implementado
- Testes/validações executadas
- Riscos ou dúvidas
- Pontos que precisam de revisão do Codex
- Confirmação (checklist)

## Instruções de Execução

1. Leia o plano aprovado do Codex Supervisor.
2. Entenda o contexto do projeto.
3. Implemente o plano conforme especificado.
4. Não expanda o escopo.
5. Não tome decisões arquiteturais grandes sozinho.
6. Se encontrar conflito ou ambiguidade, pare e reporte.
7. Execute testes relevantes.
8. Gere o relatório no formato obrigatório.

## Ao Terminar

Gere o relatório exatamente no formato solicitado em \`handoff/05-expected-report-format.md\`.

O operador humano irá:

1. Capturar o diff real do Git: \`maestro run capture-diff --run ${run.id}\`
2. Anexar seu relatório: \`maestro run attach --run ${run.id} --stage executor --file <seu-relatorio.md>\`
3. O Codex Reviewer irá revisar seu trabalho comparando com o plano aprovado e o diff real.

---

**Boa execução!**
`;
}

function renderWorkspaceNotice(workspace: RunWorkspace | undefined): string {
  if (!workspace) {
    return `## Workspace Sandbox

Aviso: esta run ainda nao tem workspace sandbox. Recomenda-se criar antes de entregar ao Kiro:

\`\`\`bash
maestro run workspace create --run <run-id>
\`\`\`
`;
  }

  return `## Workspace Sandbox

IMPORTANTE:
Trabalhe somente neste workspace sandbox:
${workspace.workspacePath}

Nao altere o repositorio original:
${workspace.sourceRepoPath}
`;
}

async function readRunFile(run: RunRecord, fileName: string): Promise<string | undefined> {
  try {
    return await fs.readFile(path.join(run.path, fileName), "utf8");
  } catch {
    return undefined;
  }
}
