import { promises as fs } from "node:fs";
import path from "node:path";
import type { Project, ProjectTask, RunRecord } from "@maestro/core";

export interface ReviewPackageResult {
  reviewDir: string;
  files: string[];
  missingDiff: boolean;
}

const REVIEW_FILES = [
  "00-read-this-first.md",
  "01-reviewer-rules.md",
  "02-original-goal.md",
  "03-approved-codex-plan.md",
  "04-executor-report.md",
  "05-git-evidence.md",
  "06-real-diff.md",
  "07-review-checklist.md",
  "08-codex-reviewer-prompt.md",
  "09-verdict-template.md"
];

export async function createReviewPackage(
  run: RunRecord,
  project: Project,
  task?: ProjectTask
): Promise<ReviewPackageResult> {
  const reviewDir = path.join(run.path, "review");
  await fs.mkdir(reviewDir, { recursive: true });

  const supervisorOutput = await readRunFile(run, "07-supervisor-output.md");
  if (!supervisorOutput) {
    throw new Error("Cannot create review package: supervisor output is missing.");
  }

  const executorOutput = await readRunFile(run, "08-executor-output.md");
  if (!executorOutput) {
    throw new Error("Cannot create review package: executor output is missing.");
  }

  const originalGoal = await readRunFile(run, "01-goal.md") || "[Goal file not found]";
  const gitBaseline = await readRunFile(run, "11-git-baseline.md");
  const gitAfter = await readRunFile(run, "12-git-after-executor.md");
  const changedFiles = await readRunFile(run, "14-changed-files.md");
  const realDiff = await readRunFile(run, "13-git-diff.md");
  const missingDiff = !realDiff;
  const diffSource = detectDiffSource(gitAfter, changedFiles, realDiff);

  await fs.writeFile(path.join(reviewDir, "00-read-this-first.md"), renderReadThisFirst(diffSource), "utf8");
  await fs.writeFile(path.join(reviewDir, "01-reviewer-rules.md"), renderReviewerRules(), "utf8");
  await fs.writeFile(path.join(reviewDir, "02-original-goal.md"), originalGoal, "utf8");
  await fs.writeFile(path.join(reviewDir, "03-approved-codex-plan.md"), supervisorOutput, "utf8");
  await fs.writeFile(path.join(reviewDir, "04-executor-report.md"), executorOutput, "utf8");
  await fs.writeFile(path.join(reviewDir, "05-git-evidence.md"), renderGitEvidence(gitBaseline, gitAfter, changedFiles, diffSource), "utf8");
  await fs.writeFile(path.join(reviewDir, "06-real-diff.md"), realDiff || renderMissingDiff(), "utf8");
  await fs.writeFile(path.join(reviewDir, "07-review-checklist.md"), renderReviewChecklist(), "utf8");
  await fs.writeFile(path.join(reviewDir, "08-codex-reviewer-prompt.md"), renderCodexReviewerPrompt(run, project, task, missingDiff, diffSource), "utf8");
  await fs.writeFile(path.join(reviewDir, "09-verdict-template.md"), renderVerdictTemplate(), "utf8");

  return {
    reviewDir,
    files: REVIEW_FILES,
    missingDiff
  };
}

function renderReadThisFirst(diffSource: string): string {
  return `# Read This First

## What is this package?

This review package was generated by Maestro to provide you (Codex Reviewer) with everything you need to review the Kiro Executor's work professionally and thoroughly.

## Key Points

- **The Kiro Executor has already implemented the task.** Your role is to review, not to implement.
- **You are the technical reviewer**, responsible for ensuring the implementation matches the approved plan.
- **Do not trust only the executor's report.** Review the real Git diff and compare it with the approved plan.
- **Your goal is to approve, reject, or request specific corrections.**
- **Follow the review rules** in \`01-reviewer-rules.md\`.
- **Use the checklist** in \`07-review-checklist.md\` to ensure thorough review.
- **When finished**, generate your verdict using the exact format in \`09-verdict-template.md\`.
- **Diff source:** ${diffSource}${diffSource === "WORKSPACE_SANDBOX" ? " (captured from the run sandbox, not the original repository)." : ""}

## Workflow

1. Read this file.
2. Read \`01-reviewer-rules.md\` to understand your review criteria.
3. Read \`02-original-goal.md\` to understand the original objective.
4. Read \`03-approved-codex-plan.md\` to understand what was approved.
5. Read \`04-executor-report.md\` to see what the executor claims to have done.
6. Read \`05-git-evidence.md\` to see the Git state before and after.
7. Read \`06-real-diff.md\` to see the actual code changes.
8. Use \`07-review-checklist.md\` to systematically review the work.
9. Use \`08-codex-reviewer-prompt.md\` as your review prompt (copy and paste it).
10. Generate your verdict using \`09-verdict-template.md\`.

## After Review

After you finish reviewing:

1. Generate your verdict following \`09-verdict-template.md\`.
2. The human operator will attach your verdict: \`maestro run attach --run <run-id> --stage reviewer --file <codex-review.md>\`.
3. The human operator will finalize the run: \`maestro run finalize --run <run-id>\`.
4. The Vault will be updated with decisions, pending items, and next actions.

## Important

- **Do not trust only the executor's report.** The executor may have missed things or made mistakes.
- **Review the real Git diff.** This is the source of truth.
- **Compare the diff with the approved plan.** Check for scope creep.
- **Check for unnecessary changes.** Files outside the scope should not be modified.
- **Verify acceptance criteria.** Were they met?
- **Be objective.** Approve if the work is good. Reject if it's not. Request corrections if needed.
- **Do not request cosmetic refactors** unless they affect functionality or maintainability.

If the real Git diff is missing, the review will be less reliable. Strongly recommend capturing it before final review.
`;
}

function renderReviewerRules(): string {
  return `# Reviewer Rules

These rules are **mandatory** for a thorough and objective review.

## Core Rules

1. **Review the real Git diff.** Do not rely solely on the executor's report.
2. **Compare the diff with the approved plan.** Verify the executor followed the plan.
3. **Check for scope creep.** Did the executor implement extra features not in the plan?
4. **Check for unnecessary file changes.** Were files outside the scope modified?
5. **Check for dependency changes.** Were dependencies added or removed without justification?
6. **Check for obvious regressions.** Does the code break existing functionality?
7. **Check for style preservation.** Was the project's existing style maintained?
8. **Verify acceptance criteria.** Were the criteria from the plan met?
9. **Do not request cosmetic refactors.** Only request changes that affect functionality or maintainability.
10. **If rejecting, provide objective corrections.** Be specific about what needs to be fixed.
11. **If approving, generate a summary for the Vault.** Include decisions, pending items, and next actions.

## What to Check

### Scope
- Did the executor follow the approved plan?
- Did the executor avoid implementing extra scope?
- Did the executor avoid making large architectural decisions without approval?

### Code Quality
- Do the changes make technical sense?
- Was the project's style preserved?
- Is there unnecessary complexity?
- Are there obvious regressions?

### Git/Diff
- Does the real diff match the executor's report?
- Were all changed files necessary?
- Are there unexpected files in the diff?
- Were sensitive files (config, env, lock files) changed without justification?

### Tests
- Did the executor report tests or validations?
- Are the reported tests sufficient?
- Are there missing tests?

### Acceptance Criteria
- Were the acceptance criteria from the approved plan met?
- If not, what is missing?

## What to Avoid

- **Do not request refactors** that are purely cosmetic.
- **Do not request changes** outside the scope of the original task.
- **Do not approve** if the executor clearly deviated from the plan without justification.
- **Do not reject** without providing specific, actionable corrections.

## Verdict Options

- **APROVADO**: The work is good and follows the approved plan. Ready to merge/deploy.
- **REPROVADO**: The work has serious issues and should not be merged. Requires significant rework.
- **PRECISA_DE_AJUSTES**: The work is mostly good but needs specific corrections before approval.

## Success Criteria

Your review will be valuable if:

- You reviewed the real Git diff, not just the report.
- You compared the diff with the approved plan.
- You checked for scope creep and unnecessary changes.
- You verified acceptance criteria.
- You provided objective, actionable feedback.
- You used the required verdict format.
`;
}

function renderGitEvidence(
  gitBaseline: string | undefined,
  gitAfter: string | undefined,
  changedFiles: string | undefined,
  diffSource: string
): string {
  return `# Git Evidence

## Diff Source

${diffSource === "WORKSPACE_SANDBOX"
    ? "Este diff foi capturado do workspace sandbox, nao do repo original."
    : "Este diff foi capturado do repo original."}

## Git Baseline (Before Execution)

${gitBaseline || "[Baseline not found]"}

## Git After Executor

${gitAfter || "[After state not captured]"}

## Changed Files

${changedFiles || "[Changed files list not captured]"}
`;
}

function renderMissingDiff(): string {
  return `# Real Diff

**[Diff real não capturado. A revisão ficará menos confiável.]**

**Atenção:** O diff real do Git não foi capturado antes de gerar este pacote de revisão.

Isso significa que você está revisando apenas com base no relatório do executor, sem evidência concreta das mudanças no código.

**Recomendação forte:** Peça ao operador para rodar:

\`\`\`bash
maestro run capture-diff --run <run-id>
\`\`\`

E então gerar o review package novamente para ter acesso ao diff real.

Revisar sem o diff real é arriscado e pode resultar em aprovação de código que não segue o plano ou contém problemas não reportados pelo executor.
`;
}

function renderReviewChecklist(): string {
  return `# Checklist de Revisão Codex

Use este checklist para garantir uma revisão completa e sistemática.

## Escopo

- [ ] O executor seguiu o plano aprovado?
- [ ] O executor evitou escopo extra?
- [ ] O executor não alterou arquitetura sem aprovação?

## Código

- [ ] As alterações fazem sentido tecnicamente?
- [ ] O estilo do projeto foi preservado?
- [ ] Não há complexidade desnecessária?
- [ ] Não há regressões óbvias?

## Git/Diff

- [ ] O diff real corresponde ao relatório do executor?
- [ ] Todos os arquivos alterados eram necessários?
- [ ] Não há arquivos inesperados?
- [ ] Não há alterações em arquivos sensíveis (config, env, lock)?

## Testes

- [ ] O executor informou testes/validações?
- [ ] Os testes informados são suficientes?
- [ ] Há testes faltando?

## Critérios de Aceite

- [ ] Os critérios de aceite do plano foram cumpridos?
- [ ] Se não, o que está faltando?

## Veredito

Escolha um:

- [ ] APROVADO - O trabalho está bom e segue o plano. Pronto para merge/deploy.
- [ ] REPROVADO - O trabalho tem problemas sérios. Requer retrabalho significativo.
- [ ] PRECISA_DE_AJUSTES - O trabalho está quase bom, mas precisa de correções específicas.

## Notas

Use o espaço abaixo para anotações durante a revisão:

---
`;
}

function renderCodexReviewerPrompt(
  run: RunRecord,
  project: Project,
  task: ProjectTask | undefined,
  missingDiff: boolean,
  diffSource: string
): string {
  const diffWarning = missingDiff
    ? `

**⚠️ ATENÇÃO: DIFF REAL NÃO CAPTURADO ⚠️**

O diff real do Git não foi capturado antes de gerar este pacote de revisão. Você está revisando apenas com base no relatório do executor, sem evidência concreta das mudanças no código.

**Isso torna a revisão menos confiável.** Recomenda-se fortemente capturar o diff real antes da revisão final.

Se possível, peça ao operador para rodar \`maestro run capture-diff --run ${run.id}\` e gerar o review package novamente.

`
    : "";

  return `# Codex Reviewer Prompt

**Copy and paste this prompt into Codex to perform the review.**

---

Você é o Codex Reviewer dentro do fluxo Maestro.

Sua função é revisar uma execução feita pelo Kiro Executor. **Não confie apenas no relatório do executor.** Revise o plano aprovado, o relatório e principalmente o diff real.
${diffWarning}
${diffSource === "WORKSPACE_SANDBOX" ? "**Importante:** este diff foi capturado do workspace sandbox, nao do repositorio original.\n" : ""}
## Informações da Run

- **Run ID:** ${run.id}
- **Project:** ${project.name} (${project.id})
- **Task ID:** ${task?.id || "none"}
${task ? `- **Task Title:** ${task.title}` : ""}

## Objetivo Original

Leia o objetivo completo em \`review/02-original-goal.md\`.

## Plano Aprovado do Codex Supervisor

Leia o plano completo em \`review/03-approved-codex-plan.md\`.

Este é o plano que o Kiro deveria ter seguido. Use-o como referência principal.

## Relatório do Executor

Leia o relatório completo em \`review/04-executor-report.md\`.

Este é o que o Kiro afirma ter feito. **Não confie cegamente.** Verifique contra o diff real.

## Evidência Git

Leia a evidência completa em \`review/05-git-evidence.md\`.

Isso mostra o estado do repositório antes e depois da execução, e a lista de arquivos alterados.

## Diff Real

Leia o diff completo em \`review/06-real-diff.md\`.

**Este é o mais importante.** O diff real mostra exatamente o que foi alterado no código. Compare com o plano aprovado e com o relatório do executor.

## Checklist de Revisão

Use o checklist em \`review/07-review-checklist.md\` para garantir uma revisão sistemática.

## Regras de Revisão

Leia as regras completas em \`review/01-reviewer-rules.md\`.

Resumo das regras principais:

1. Revise o diff real, não apenas o relatório.
2. Compare o diff com o plano aprovado.
3. Verifique se o executor expandiu o escopo.
4. Verifique se arquivos fora do necessário foram alterados.
5. Verifique se dependências foram alteradas sem justificativa.
6. Verifique se há regressões óbvias.
7. Verifique se o estilo do projeto foi preservado.
8. Verifique se os critérios de aceite foram cumpridos.
9. Não peça refatorações cosméticas desnecessárias.
10. Se reprovar, gere correções objetivas.
11. Se aprovar, gere resumo para atualizar o Vault.

## Instruções de Revisão

1. Leia o objetivo original e o plano aprovado.
2. Leia o relatório do executor.
3. **Revise o diff real cuidadosamente.**
4. Compare o diff com o plano aprovado.
5. Verifique se há escopo extra ou arquivos inesperados.
6. Verifique se os critérios de aceite foram cumpridos.
7. Use o checklist para garantir revisão completa.
8. Decida: APROVADO, REPROVADO ou PRECISA_DE_AJUSTES.
9. Gere seu veredito no formato obrigatório.

## Formato de Veredito Obrigatório

Ao terminar, produza seu veredito usando **exatamente** o formato de \`review/09-verdict-template.md\`.

O veredito deve incluir:

- Status (APROVADO, REPROVADO ou PRECISA_DE_AJUSTES)
- Resumo da revisão
- Se o executor seguiu o plano
- Problemas encontrados
- Arquivos que precisam de correção
- Correções obrigatórias
- Melhorias opcionais
- Testes/validações recomendadas
- Atualização sugerida para o Vault (decisões, pendências, próximos passos)
- Confirmação (checklist)

## Ao Terminar

Gere o veredito exatamente no formato solicitado em \`review/09-verdict-template.md\`.

O operador humano irá:

1. Anexar seu veredito: \`maestro run attach --run ${run.id} --stage reviewer --file <codex-review.md>\`
2. Finalizar a run: \`maestro run finalize --run ${run.id}\`
3. O Vault será atualizado com decisões, pendências e próximos passos.

---

**Boa revisão!**
`;
}

function renderVerdictTemplate(): string {
  return `# Veredito do Codex Reviewer

## Status

Escolha um:

- [ ] APROVADO
- [ ] REPROVADO
- [ ] PRECISA_DE_AJUSTES

## Resumo da revisão

[Forneça um resumo breve da sua revisão]

## O executor seguiu o plano?

[Sim/Não/Parcialmente - Explique]

## Problemas encontrados

[Liste todos os problemas encontrados durante a revisão]

- Problema 1
- Problema 2
- Problema 3

## Arquivos que precisam de correção

[Liste os arquivos específicos que precisam ser corrigidos]

- path/to/file1.ts - [motivo]
- path/to/file2.ts - [motivo]

## Correções obrigatórias

[Liste as correções que DEVEM ser feitas antes da aprovação]

1. Correção 1
2. Correção 2
3. Correção 3

## Melhorias opcionais

[Liste melhorias que seriam boas, mas não são obrigatórias]

- Melhoria 1
- Melhoria 2

## Testes/validações recomendadas

[Liste testes ou validações que devem ser executados]

- Teste 1
- Teste 2
- Validação 1

## Atualização sugerida para o Vault

### Decisões

[Decisões técnicas ou arquiteturais tomadas durante esta implementação]

### Pendências

[Itens que ficaram pendentes e precisam ser tratados futuramente]

### Próximos passos

[Próximas ações recomendadas para o projeto]

## Confirmação

- [ ] Revisei o plano aprovado
- [ ] Revisei o relatório do executor
- [ ] Revisei o diff real
- [ ] Comparei o diff com o plano
- [ ] Verifiquei possível escopo extra
- [ ] Verifiquei arquivos alterados
- [ ] Verifiquei critérios de aceite
- [ ] Verifiquei testes/validações
`;
}

async function readRunFile(run: RunRecord, fileName: string): Promise<string | undefined> {
  try {
    return await fs.readFile(path.join(run.path, fileName), "utf8");
  } catch {
    return undefined;
  }
}

function detectDiffSource(...contents: Array<string | undefined>): "WORKSPACE_SANDBOX" | "ORIGINAL_REPO" {
  return contents.some((content) => content?.includes("WORKSPACE_SANDBOX")) ? "WORKSPACE_SANDBOX" : "ORIGINAL_REPO";
}
